spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/user/**
        - id: room
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/room/**
        - id: booking
          uri: http://localhost:8092
          predicates:
            - Path=/api/v1/booking

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
    healthcheck:
      enabled: true
