spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URI:jdbc:mariadb://localhost:3307/hoteldb}
    username: ${MARIADB_ROOT_USER:root}
    password: ${MARIADB_ROOT_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8091

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA-SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true