spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URI:jdbc:mysql://localhost:3306/hoteldb}
    username: ${MYSQL_ROOT_USER:root}
    password: ${MYSQL_ROOT_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8092
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA-SERVER:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true

microservices:
  user-uri: ${MICROSERVICE-USER:http://localhost:8090}
  room-uri: ${MICROSERVICE-ROOM:http://localhost:8091}