spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URI:jdbc:postgresql://localhost:5432/hoteldb}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA-SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
